/// <reference types="react/canary" />
import type { Metadata } from "next";
import { ViewTransition } from "react";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SiteNav } from "@/components/site/SiteNav";
import { SiteFooter } from "@/components/site/SiteFooter";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    metadataBase: new URL("https://retreejs.dev"),
    title: {
        default: "Retree — state that matches your component tree",
        template: "%s | Retree",
    },
    description:
        "Retree is a lightweight React state tree library in TypeScript. Mutate plain objects and classes; exactly the components that read them re-render.",
    openGraph: {
        siteName: "Retree",
        type: "website",
        url: "https://retreejs.dev",
    },
    twitter: {
        card: "summary_large_image",
    },
};

/**
 * Applies the persisted theme before first paint. Dark is the default; only
 * an explicit "light" choice (or light OS preference when no choice is
 * stored) sets the attribute, so there is no flash for either audience.
 */
const themeScript = `(function () {
    try {
        var stored = localStorage.getItem("retree-theme");
        var theme = stored === "light" || stored === "dark"
            ? stored
            : window.matchMedia("(prefers-color-scheme: light)").matches
              ? "light"
              : "dark";
        if (theme === "light") {
            document.documentElement.dataset.theme = "light";
        }
    } catch (e) {}
})();`;

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <head>
                <script dangerouslySetInnerHTML={{ __html: themeScript }} />
                {/* Static Sandpack CSS, generated by
                    scripts/generate-sandpack-css.mjs. A plain stylesheet keeps
                    sandpack-react + CodeMirror out of the shared client
                    bundle while live demos still SSR without a style flash.
                    It lives in public/, outside the bundler pipeline, so the
                    no-css-tags rule does not apply. */}
                {/* eslint-disable-next-line @next/next/no-css-tags */}
                <link rel="stylesheet" href="/sandpack.css" />
            </head>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <SiteNav />
                {/* page-fade: 150 ms cross-fade on route navigations; see the
                    ::view-transition rules in globals.css. */}
                <ViewTransition default="page-fade">
                    <div className="min-h-[calc(100vh-3.5rem)]">{children}</div>
                </ViewTransition>
                <SiteFooter />
            </body>
        </html>
    );
}
