/**
 * Generates an original, upbeat music track as music.wav (or music-short.wav).
 *
 * Style: bright, driving, modern — marimba-ish plucks with ping-pong echo,
 * a funky octave-popping bass, claps on 2 & 4, driving hats, bell pings,
 * a pentatonic hook in the lift, noise risers into each section, and a
 * held Cmaj9 resolve under the CTA. C major at 112 BPM, I–V–vi–IV.
 * Fully deterministic (seeded LFSR noise, fixed patterns).
 * Original composition generated by this script → royalty-free.
 *
 * Modes: `node music.mjs` → 42.9s (full cut); `node music.mjs short` → 29.9s.
 * Output: 44100 Hz, 16-bit PCM, stereo.
 */
import { writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const MODE = process.argv[2] === "short" ? "short" : "full";
const SR = 44100;
const DURATION = MODE === "short" ? 29.9 : 42.9;
const N = Math.round(SR * DURATION);
const BPM = 112;
const BEAT = 60 / BPM; // ≈0.536 s
const BAR = BEAT * 4; // ≈2.143 s
// Sections (bar indices): intro 0–1, groove 2…, lift = last LIFT_BARS bars
// before RESOLVE_BAR, resolve at RESOLVE_BAR (full: 36.43s, short: 23.57s).
const RESOLVE_BAR = MODE === "short" ? 11 : 17;
const LIFT_BARS = MODE === "short" ? 3 : 4;
const LIFT_START = RESOLVE_BAR - LIFT_BARS;
const FADE_IN = 0.5;
const FADE_OUT_START = MODE === "short" ? 26.6 : 39.6;
const FADE_OUT_END = MODE === "short" ? 29.6 : 42.6;

const left = new Float32Array(N);
const right = new Float32Array(N);

const midiHz = (m) => 440 * Math.pow(2, (m - 69) / 12);
function panGains(pan) {
  const a = (pan * Math.PI) / 2;
  return [Math.cos(a), Math.sin(a)];
}

// ---------------------------------------------------------------------------
// Instruments
// ---------------------------------------------------------------------------

/** Marimba-like pluck with optional dotted-eighth ping-pong echo. */
function addPluck(start, midi, gain, pan, { decay = 6.5, echo = true } = {}) {
  const f = midiHz(midi);
  const dur = Math.min(1.4, 4 / decay);
  const s0 = Math.floor(start * SR);
  const s1 = Math.min(N, s0 + Math.floor(dur * SR));
  const [gL, gR] = panGains(pan);
  for (let i = s0; i < s1; i++) {
    const tt = (i - s0) / SR;
    const attack = Math.min(tt / 0.004, 1);
    const w = 2 * Math.PI * f * tt;
    const sample =
      (Math.sin(w) * Math.exp(-tt * decay) +
        0.35 * Math.sin(2 * w) * Math.exp(-tt * decay * 1.8) +
        0.18 * Math.sin(4 * w) * Math.exp(-tt * decay * 3.2)) *
      gain *
      attack;
    left[i] += sample * gL;
    right[i] += sample * gR;
  }
  if (echo) {
    addPluck(start + BEAT * 0.75, midi, gain * 0.28, 1 - pan, {
      decay: decay * 1.3,
      echo: false,
    });
  }
}

/** Bright bell ping: sine + inharmonic partial, long ring. */
function addBell(start, midi, gain, pan) {
  const f = midiHz(midi);
  const s0 = Math.floor(start * SR);
  const s1 = Math.min(N, s0 + Math.floor(1.6 * SR));
  const [gL, gR] = panGains(pan);
  for (let i = s0; i < s1; i++) {
    const tt = (i - s0) / SR;
    const attack = Math.min(tt / 0.003, 1);
    const sample =
      (Math.sin(2 * Math.PI * f * tt) * Math.exp(-tt * 2.6) +
        0.35 * Math.sin(2 * Math.PI * f * 3.03 * tt) * Math.exp(-tt * 5.2)) *
      gain *
      attack;
    left[i] += sample * gL;
    right[i] += sample * gR;
  }
}

/** Warm pad: detuned harmonic-sum voices spread L/R, slow attack. */
function addPad(start, dur, midis, gain) {
  const s0 = Math.floor(start * SR);
  const s1 = Math.min(N, Math.floor((start + dur) * SR));
  const voices = midis.map((m) => {
    const f = midiHz(m);
    return { fL: f * 1.0015, fR: f * 0.9985 };
  });
  for (let i = s0; i < s1; i++) {
    const tt = (i - s0) / SR;
    const attack = Math.min(tt / 0.5, 1);
    const release = Math.min((dur - tt) / 0.6, 1);
    const env = gain * attack * Math.max(release, 0);
    let sL = 0;
    let sR = 0;
    for (const v of voices) {
      const wL = 2 * Math.PI * v.fL * tt;
      const wR = 2 * Math.PI * v.fR * tt;
      sL += Math.sin(wL) + 0.25 * Math.sin(2 * wL) + 0.11 * Math.sin(3 * wL);
      sR += Math.sin(wR) + 0.25 * Math.sin(2 * wR) + 0.11 * Math.sin(3 * wR);
    }
    left[i] += sL * env;
    right[i] += sR * env;
  }
}

/** Punchy bass note with a whisper of 2nd harmonic. Centered. */
function addBass(start, dur, midi, gain) {
  const f = midiHz(midi);
  const s0 = Math.floor(start * SR);
  const s1 = Math.min(N, Math.floor((start + dur) * SR));
  for (let i = s0; i < s1; i++) {
    const tt = (i - s0) / SR;
    const attack = Math.min(tt / 0.008, 1);
    const release = Math.min((dur - tt) / 0.05, 1);
    const w = 2 * Math.PI * f * tt;
    const sample =
      (Math.sin(w) + 0.15 * Math.sin(2 * w)) *
      gain *
      attack *
      Math.max(release, 0) *
      Math.exp(-tt * 2.2);
    left[i] += sample;
    right[i] += sample;
  }
}

/** Low-passed sine thump, 85→45 Hz. Centered. */
function addKick(start, gain) {
  const s0 = Math.floor(start * SR);
  const s1 = Math.min(N, s0 + Math.floor(SR * 0.15));
  for (let i = s0; i < s1; i++) {
    const tt = (i - s0) / SR;
    const attack = Math.min(tt / 0.003, 1);
    const f = 45 + 40 * Math.exp(-tt * 30);
    const sample =
      Math.sin(2 * Math.PI * f * tt) * gain * attack * Math.exp(-tt * 16);
    left[i] += sample;
    right[i] += sample;
  }
}

// Seeded LFSR-style noise — deterministic.
let noiseState = 0x2f6e15;
function nextNoise() {
  noiseState = (noiseState * 1103515245 + 12345) & 0x7fffffff;
  return noiseState / 0x3fffffff - 1;
}

/** Short filtered-noise hat. */
function addHat(start, gain, pan, dur = 0.03) {
  const s0 = Math.floor(start * SR);
  const s1 = Math.min(N, s0 + Math.floor(SR * dur));
  const [gL, gR] = panGains(pan);
  let prev = nextNoise();
  for (let i = s0; i < s1; i++) {
    const tt = (i - s0) / SR;
    const n = nextNoise();
    const hp = (n - prev) * 0.5;
    prev = n;
    const sample = hp * gain * Math.exp(-tt * (2.2 / dur / 10) * 10);
    left[i] += sample * gL;
    right[i] += sample * gR;
  }
}

/** Clap: three quick mid-band noise bursts. */
function addClap(start, gain) {
  for (const [offset, g] of [[0, 0.7], [0.012, 0.55], [0.026, 1]]) {
    const s0 = Math.floor((start + offset) * SR);
    const s1 = Math.min(N, s0 + Math.floor(SR * 0.1));
    let prev = nextNoise();
    let smooth = 0;
    for (let i = s0; i < s1; i++) {
      const tt = (i - s0) / SR;
      const n = nextNoise();
      const hp = (n - prev) * 0.5;
      prev = n;
      smooth = smooth * 0.55 + hp * 0.45; // tame the top end a touch
      const sample = smooth * gain * g * Math.exp(-tt * 42);
      left[i] += sample * 0.95;
      right[i] += sample * 1.05;
    }
  }
}

/** Noise riser sweeping into a section boundary. */
function addRiser(endAt, dur, gain) {
  const s0 = Math.max(0, Math.floor((endAt - dur) * SR));
  const s1 = Math.min(N, Math.floor(endAt * SR));
  let prev = nextNoise();
  for (let i = s0; i < s1; i++) {
    const p = (i - s0) / (s1 - s0);
    const n = nextNoise();
    const hp = (n - prev) * 0.5;
    prev = n;
    const sample = hp * gain * p * p;
    left[i] += sample * (1 - p * 0.5);
    right[i] += sample * (0.5 + p * 0.5);
  }
}

/** Cymbal-ish crash: bright noise with a long decay. */
function addCrash(start, gain) {
  const s0 = Math.floor(start * SR);
  const s1 = Math.min(N, s0 + Math.floor(SR * 1.1));
  let prev = nextNoise();
  for (let i = s0; i < s1; i++) {
    const tt = (i - s0) / SR;
    const n = nextNoise();
    const hp = (n - prev) * 0.5;
    prev = n;
    const sample = hp * gain * Math.exp(-tt * 4.5);
    left[i] += sample * 1.05;
    right[i] += sample * 0.95;
  }
}

// ---------------------------------------------------------------------------
// Composition — C major, I–V–vi–IV, bright voicings
// ---------------------------------------------------------------------------

// [bass midi, pad chord midis, arpeggio midis]
const Cmaj9 = [36, [48, 55, 62, 64], [60, 64, 67, 71]]; // C2 | C3 G3 D4 E4
const Gadd9 = [43, [43, 50, 54, 57], [55, 59, 62, 67]]; // G2 | G2 D3 F#3 A3
const Am7 = [33, [45, 52, 55, 60], [57, 60, 64, 67]]; // A1 | A2 E3 G3 C4
const Fmaj9 = [41, [41, 48, 52, 57], [53, 57, 60, 64]]; // F2 | F2 C3 E3 A3
const PROG = [Cmaj9, Gadd9, Am7, Fmaj9];
const chordAt = (bar) => (bar === 0 ? Cmaj9 : bar === 1 ? Fmaj9 : PROG[(bar - 2) % 4]);

// Eighth-note arpeggio patterns (indices into the chord's arp notes).
const PATTERNS = [
  [0, 2, 1, 3, 2, 0, 3, 1],
  [0, 1, 3, 2, 1, 3, 0, 2],
];
const PANS = [0.42, 0.6, 0.36, 0.64, 0.45, 0.58, 0.4, 0.55];
// Funky bass steps per bar: [eighth-note position, semitone offset from root].
const BASS_STEPS = [[0, 0], [3, 0], [4, 12], [6, 0], [7, 7]];
// Pentatonic hook, one two-bar phrase, [eighth position, midi].
const HOOK = [
  [0, 76], [2, 74], [3, 72], [5, 67], [6, 69],
  [8, 72], [10, 74], [11, 76], [13, 79], [14, 76],
];

for (let bar = 0; bar < RESOLVE_BAR; bar++) {
  const t0 = bar * BAR;
  const [bassMidi, padMidis, arp] = chordAt(bar);
  const intro = bar < 2;
  const lift = bar >= LIFT_START;

  addPad(t0, BAR + 0.25, padMidis, intro ? 0.032 : lift ? 0.046 : 0.038);

  if (intro) {
    // Sparse ringing plucks + a bell to set the palette.
    addPluck(t0 + BEAT, arp[0] + 12, 0.075, 0.44, { decay: 4.5 });
    addPluck(t0 + BEAT * 2.5, arp[2], 0.06, 0.56, { decay: 4.5 });
    if (bar === 1) addBell(t0 + BEAT * 3, arp[1] + 12, 0.045, 0.62);
    continue;
  }

  // Main arpeggio — driving eighths.
  const pattern = PATTERNS[bar % 2];
  for (let n = 0; n < 8; n++) {
    addPluck(t0 + n * (BEAT / 2), arp[pattern[n]], 0.115, PANS[n]);
    if (lift && n % 2 === 0) {
      addPluck(t0 + n * (BEAT / 2), arp[pattern[n]] + 12, 0.04, 1 - PANS[n], {
        decay: 8,
        echo: false,
      });
    }
  }

  // Hook melody rides on top during the lift (two-bar phrase).
  if (lift) {
    const phrase = (bar - LIFT_START) % 2;
    for (const [pos, midi] of HOOK) {
      if (Math.floor(pos / 8) !== phrase) continue;
      addPluck(t0 + (pos % 8) * (BEAT / 2), midi, 0.085, 0.52, { decay: 5, echo: false });
    }
  }

  // Bell ping every other bar (chord color, way up top).
  if (bar % 2 === 0) addBell(t0, arp[3] + 12, 0.035, bar % 4 === 0 ? 0.4 : 0.6);

  // Funky bass — octave pops.
  for (const [step, offset] of BASS_STEPS) {
    const short = offset !== 0;
    addBass(t0 + step * (BEAT / 2), short ? BEAT * 0.45 : BEAT * 0.9, bassMidi + offset, short ? 0.1 : 0.13);
  }

  // Drums: kick 1 & 3, claps 2 & 4, eighth hats (16ths in the lift).
  addKick(t0, 0.27);
  addKick(t0 + BEAT * 2, 0.23);
  addClap(t0 + BEAT, 0.14);
  addClap(t0 + BEAT * 3, 0.15);
  for (let n = 0; n < 8; n++) {
    addHat(t0 + n * (BEAT / 2), n % 2 === 1 ? 0.055 : 0.028, n % 4 === 1 ? 0.38 : 0.62);
  }
  if (lift) {
    for (let n = 0; n < 16; n++) {
      if (n % 2 === 1) addHat(t0 + n * (BEAT / 4), 0.02, 0.5, 0.02);
    }
    addHat(t0 + BEAT * 3.5, 0.07, 0.5, 0.09); // open-ish hat pushing forward
  }
  // Little clap fill at the end of the bar right before a section change.
  if (bar === LIFT_START - 1 || bar === RESOLVE_BAR - 1) {
    for (let k = 0; k < 4; k++) addClap(t0 + BEAT * 3 + k * (BEAT / 4), 0.08 + k * 0.02);
  }
}

// Risers + crashes at the section boundaries.
addRiser(2 * BAR, 1.6, 0.05); // into the groove
addRiser(LIFT_START * BAR, 1.8, 0.07); // into the lift
addRiser(RESOLVE_BAR * BAR, 1.8, 0.07); // into the resolve
addCrash(2 * BAR, 0.08);
addCrash(LIFT_START * BAR, 0.11);

// Resolve: impact + held Cmaj9 + rolled arpeggio + one last bell echo.
const tEnd = RESOLVE_BAR * BAR;
addCrash(tEnd, 0.13);
addKick(tEnd, 0.3);
addPad(tEnd, DURATION - tEnd - 0.4, [48, 55, 59, 64, 62], 0.045);
addBass(tEnd, 4.5, 36, 0.14);
const roll = [60, 64, 67, 71, 74];
for (let k = 0; k < roll.length; k++) {
  addPluck(tEnd + k * 0.085, roll[k], 0.09, 0.38 + k * 0.06, { decay: 3.2, echo: false });
}
addPluck(tEnd + BEAT * 2, 76, 0.055, 0.6, { decay: 3 });
addBell(tEnd + BEAT * 4, 84, 0.04, 0.55);

// ---------------------------------------------------------------------------
// Master: fade in/out, soft clip, normalize
// ---------------------------------------------------------------------------
for (let i = 0; i < N; i++) {
  const t = i / SR;
  let fade = Math.min(t / FADE_IN, 1);
  if (t >= FADE_OUT_END) {
    fade = 0;
  } else if (t > FADE_OUT_START) {
    const x = (t - FADE_OUT_START) / (FADE_OUT_END - FADE_OUT_START);
    fade *= 0.5 * (1 + Math.cos(Math.PI * x));
  }
  left[i] = Math.tanh(left[i] * 1.25) * fade;
  right[i] = Math.tanh(right[i] * 1.25) * fade;
}

let peak = 0;
for (let i = 0; i < N; i++) {
  peak = Math.max(peak, Math.abs(left[i]), Math.abs(right[i]));
}
const norm = 0.7 / peak;

// Write 16-bit stereo PCM WAV.
const data = Buffer.alloc(N * 4);
for (let i = 0; i < N; i++) {
  data.writeInt16LE(Math.round(left[i] * norm * 32767), i * 4);
  data.writeInt16LE(Math.round(right[i] * norm * 32767), i * 4 + 2);
}
const header = Buffer.alloc(44);
header.write("RIFF", 0);
header.writeUInt32LE(36 + data.length, 4);
header.write("WAVE", 8);
header.write("fmt ", 12);
header.writeUInt32LE(16, 16);
header.writeUInt16LE(1, 20);
header.writeUInt16LE(2, 22);
header.writeUInt32LE(SR, 24);
header.writeUInt32LE(SR * 4, 28);
header.writeUInt16LE(4, 32);
header.writeUInt16LE(16, 34);
header.write("data", 36);
header.writeUInt32LE(data.length, 40);
const outName = MODE === "short" ? "music-short.wav" : "music.wav";
writeFileSync(path.join(__dirname, outName), Buffer.concat([header, data]));

console.log(
  `${outName} written: ${DURATION}s stereo @ ${SR} Hz, ` +
    `${44 + data.length} bytes, pre-normalize peak ${peak.toFixed(4)}, normalized to 0.7`
);
